version: "3.1"
services:

  mysql:
    image: hypriot/rpi-mysql
    container_name: mysql
#    volumes:
#      - ./data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=volkszaehler
      - MYSQL_DATABASE=volkszaehler
      - MYSQL_USER=vz
      - MYSQL_PASSWORD=demo

  volkszaehler:
    image: volkszaehler/volkszaehler
    container_name: volkszaehler
    ports:
      - "8080:8080"
    depends_on:
      - mysql
